  <link rel="stylesheet" src="/Dashboard/froala/css/froala_editor.css">
  <link rel="stylesheet" src="/Dashboard/froala/css/froala_style.css">
  <link rel="stylesheet" src="/Dashboard/froala/css/plugins/code_view.css">
  <link rel="stylesheet" src="/Dashboard/froala/css/plugins/colors.css">
  <link rel="stylesheet" src="/Dashboard/froala/css/plugins/emoticons.css">
  <link rel="stylesheet" src="/Dashboard/froala/css/plugins/image_manager.css">
  <link rel="stylesheet" src="/Dashboard/froala/css/plugins/image.css">
  <link rel="stylesheet" src="/Dashboard/froala/css/plugins/line_breaker.css">
  <link rel="stylesheet" src="/Dashboard/froala/css/plugins/table.css">
  <link rel="stylesheet" src="/Dashboard/froala/css/plugins/char_counter.css">
  <link rel="stylesheet" src="/Dashboard/froala/css/plugins/video.css">
  <link rel="stylesheet" src="/Dashboard/froala/css/plugins/fullscreen.css">
  <link rel="stylesheet" src="/Dashboard/froala/css/plugins/file.css">
