  <script type="text/javascript" src="/Dashboard/froala/js/froala_editor.min.js"></script>
  <script type="text/javascript" src="/Dashboard/froala/js/plugins/align.min.js"></script>
  <script type="text/javascript" src="/Dashboard/froala/js/plugins/code_beautifier.min.js"></script>
  <script type="text/javascript" src="/Dashboard/froala/js/plugins/code_view.min.js"></script>
  <script type="text/javascript" src="/Dashboard/froala/js/plugins/colors.min.js"></script>
  <script type="text/javascript" src="/Dashboard/froala/js/plugins/draggable.min.js"></script>
  <script type="text/javascript" src="/Dashboard/froala/js/plugins/emoticons.min.js"></script>
  <script type="text/javascript" src="/Dashboard/froala/js/plugins/font_size.min.js"></script>
  <script type="text/javascript" src="/Dashboard/froala/js/plugins/font_family.min.js"></script>
  <script type="text/javascript" src="/Dashboard/froala/js/plugins/image.min.js"></script>
  <script type="text/javascript" src="/Dashboard/froala/js/plugins/file.min.js"></script>
  <script type="text/javascript" src="/Dashboard/froala/js/plugins/image_manager.min.js"></script>
  <script type="text/javascript" src="/Dashboard/froala/js/plugins/line_breaker.min.js"></script>
  <script type="text/javascript" src="/Dashboard/froala/js/plugins/link.min.js"></script>
  <script type="text/javascript" src="/Dashboard/froala/js/plugins/lists.min.js"></script>
  <script type="text/javascript" src="/Dashboard/froala/js/plugins/paragraph_format.min.js"></script>
  <script type="text/javascript" src="/Dashboard/froala/js/plugins/paragraph_style.min.js"></script>
  <script type="text/javascript" src="/Dashboard/froala/js/plugins/video.min.js"></script>
  <script type="text/javascript" src="/Dashboard/froala/js/plugins/table.min.js"></script>
  <script type="text/javascript" src="/Dashboard/froala/js/plugins/url.min.js"></script>
  <script type="text/javascript" src="/Dashboard/froala/js/plugins/entities.min.js"></script>
  <script type="text/javascript" src="/Dashboard/froala/js/plugins/char_counter.min.js"></script>
  <script type="text/javascript" src="/Dashboard/froala/js/plugins/inline_style.min.js"></script>
  <script type="text/javascript" src="/Dashboard/froala/js/plugins/save.min.js"></script>
  <script type="text/javascript" src="/Dashboard/froala/js/plugins/fullscreen.min.js"></script>
  <script type="text/javascript" src="/Dashboard/froala/js/languages/ro.js"></script>
